apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-apps-db-ha-postgresql-0
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/nfs/okd/data-apps-db-ha-postgresql-0
    server: 192.168.122.1
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-apps-db-ha-postgresql-1
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/nfs/okd/data-apps-db-ha-postgresql-1
    server: 192.168.122.1
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-apps-db-ha-postgresql-2
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/nfs/okd/data-apps-db-ha-postgresql-2
    server: 192.168.122.1
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
