apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-apps-db-ha-postgresql-0
  namespace: databases
  labels:
    app.kubernetes.io/instance: apps-db-ha
    volume-index: "0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-apps-db-ha-postgresql-1
  namespace: databases
  labels:
    app.kubernetes.io/instance: apps-db-ha
    volume-index: "1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-apps-db-ha-postgresql-2
  namespace: databases
  labels:
    app.kubernetes.io/instance: apps-db-ha
    volume-index: "2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs
