apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-cert
  namespace: identity
  labels:
    kuma.io/mesh: default
spec:
  secretName: auth-tls
  commonName: auth.blocksafe.home
  dnsNames:
    - auth.blocksafe.home
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
