apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-cert
  namespace: identity
spec:
  secretName: auth-tls
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  commonName: auth.blocksafe.home
  dnsNames:
    - auth.blocksafe.home
