auth:
  existingSecret: keycloak-admin-secret
  passwordSecretKey: admin-password
  adminUser: keycloak_admin

postgresql:
  enabled: false

externalDatabase:
  host: 192.168.122.101
  port: 5432
  user: keycloak
  existingSecret: keycloak-db-secret
  existingSecretPasswordKey: password
  database: keycloak

service:
  type: ClusterIP

serviceAccount:
  create: false
  name: keycloak-sa

ingress:
  enabled: false

proxy: edge
extraEnvVars:
  - name: KC_PROXY
    value: "edge"
