apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: kong-ingress-scc
allowPrivilegedContainer: false
allowPrivilegeEscalation: false
allowedCapabilities:
  - NET_BIND_SERVICE
requiredDropCapabilities:
  - ALL
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
