env:
  database: "postgres"
  pg_host: "192.168.122.101"
  pg_port: 5432
  pg_user: kong
  pg_password: kong-db-secret
  pg_database: kong
  KONG_PORTAL_GUI_HOST: "kongmanager.blocksafe.local"

deployment:
  serviceAccount:
    create: false
    name: kong-ingress-sa

ingressController:
  enabled: true
  installCRDs: true
  serviceAccount:
    create: false
    name: kong-ingress-sa

proxy:
  enabled: true
  type: LoadBalancer
  annotations:
    metallb.universe.tf/address-pool: my-pool
  loadBalancerIP: 192.168.122.100
  http:
    enabled: false
  tls:
    enabled: true
    servicePort: 443
  serviceAccount:
    create: false
    name: kong-ingress-sa

admin:
  enabled: true
  type: LoadBalancer
  annotations:
    metallb.universe.tf/address-pool: my-pool
  loadBalancerIP: 192.168.122.103
  http:
    enabled: false
  tls:
    enabled: true
    servicePort: 443

manager:
  enabled: true
  type: LoadBalancer
  annotations:
    metallb.universe.tf/address-pool: my-pool
  loadBalancerIP: 192.168.122.102
  http:
    enabled: false
  tls:
    enabled: true
    servicePort: 443

portal:
  enabled: false

podSecurityContext:
  fsGroup: 1000710000

containerSecurityContext:
  runAsUser: 1000710000
  runAsNonRoot: true

migrations:
  preUpgrade: true
  postUpgrade: true
